dist: trusty

os:
- linux
arch:
- amd64
- arm64

language: go

go:
- "1.14"
- tip

env:
- GO111MODULE=on

install:
- go get github.com/mfridman/tparse
- go get github.com/mattn/goveralls
- go get github.com/lawrencewoodman/roveralls

script:
- make check
- make coveralls

jobs:
    exclude:
        - os: linux
          arch: arm64
          go: tip
